import type { CatalogApp } from './types';
import { AP, BC, BF, DL, DN, FP, OI, PC, SN, W } from './types';

const a = (
  base: Omit<CatalogApp, 'iconKey' | 'status' | 'version'> & Partial<Pick<CatalogApp, 'iconKey' | 'status' | 'version'>>
): CatalogApp => ({
  iconKey: base.slug,
  status: 'verified',
  version: null,
  ...base
});

export const appsB: CatalogApp[] = [
  a({
    slug: 'visual-studio-code',
    name: 'Visual Studio Code',
    vendor: 'Microsoft',
    categorySlug: 'desenvolvimento',
    tagline: 'Editor de código moderno e extensível.',
    description:
      'Editor de código gratuito da Microsoft com IntelliSense, depuração integrada, Git embutido e o maior ecossistema de extensões do mercado. O editor mais popular entre desenvolvedores.',
    websiteUrl: 'https://code.visualstudio.com/',
    license: 'freeware',
    color: '#007ACC',
    popularity: 98,
    updatedDaysAgo: 1,
    tags: ['editor de código', 'ide', 'microsoft', 'typescript', 'python', 'visual studio', 'vscode', 'visual'],
    oss: ['windows', 'macos', 'linux'],
    archs: ['x64', 'arm64'],
    alternatives: ['cursor', 'zed', 'vscodium'],
    packages: [
      W('Microsoft.VisualStudioCode'),
      BC('visual-studio-code'),
      FP('com.visualstudio.code', { source: 'official' }),
      SN('code', { classic: true }),
      PC('code', { repository: 'extra' }),
      DL('https://code.visualstudio.com/Download', 'linux')
    ]
  }),
  a({
    slug: 'vscodium',
    name: 'VSCodium',
    vendor: 'VSCodium Project',
    categorySlug: 'desenvolvimento',
    tagline: 'Binários livres do VS Code, sem telemetria.',
    description:
      'Builds open source do VS Code sem telemetria nem rastreamento da Microsoft, mantendo compatibilidade com a maioria das extensões via Open VSX.',
    websiteUrl: 'https://vscodium.com/',
    license: 'open_source',
    color: '#2F80ED',
    popularity: 52,
    updatedDaysAgo: 6,
    tags: ['editor de código', 'open source', 'telemetria zero'],
    oss: ['windows', 'macos', 'linux'],
    archs: ['x64', 'arm64'],
    alternatives: ['visual-studio-code'],
    packages: [
      W('VSCodium.VSCodium'),
      BC('vscodium'),
      FP('com.vscodium.codium', { source: 'official' })
    ]
  }),
  a({
    slug: 'cursor',
    name: 'Cursor',
    vendor: 'Anysphere',
    categorySlug: 'desenvolvimento',
    tagline: 'Editor de código com IA integrada.',
    description:
      'Fork do VS Code com assistente de IA nativo, edição multiarquivo por prompt e autocomplete contextual para acelerar desenvolvimento.',
    websiteUrl: 'https://cursor.com/',
    license: 'freemium',
    color: '#5A5AF5',
    popularity: 70,
    updatedDaysAgo: 1,
    tags: ['editor de código', 'ia', 'autocomplete'],
    oss: ['windows', 'macos', 'linux'],
    archs: ['x64', 'arm64'],
    alternatives: ['visual-studio-code', 'zed'],
    packages: [W('Anysphere.Cursor'), BC('cursor')]
  }),
  a({
    slug: 'zed',
    name: 'Zed',
    vendor: 'Zed Industries',
    categorySlug: 'desenvolvimento',
    tagline: 'Editor escrito em Rust, focado em performance.',
    description:
      'Editor de código de altíssima performance criado pelos autores do Atom, com colaboração em tempo real, LSP integrado e interface enxuta.',
    websiteUrl: 'https://zed.dev/',
    license: 'open_source',
    color: '#0F6FFF',
    popularity: 56,
    updatedDaysAgo: 2,
    tags: ['editor de código', 'rust', 'performance'],
    oss: ['macos', 'linux', 'windows'],
    archs: ['x64', 'arm64'],
    alternatives: ['visual-studio-code'],
    packages: [BC('zed'), FP('dev.zed.Zed', { source: 'official' }), W('ZedIndustries.Zed')]
  }),
  a({
    slug: 'visual-studio-2022',
    name: 'Visual Studio 2022 Community',
    vendor: 'Microsoft',
    categorySlug: 'desenvolvimento',
    tagline: 'IDE completa para .NET e C++ no Windows.',
    description:
      'IDE completa da Microsoft para desenvolvimento .NET, C++, Unity e Azure. A versão Community é gratuita para uso individual.',
    websiteUrl: 'https://visualstudio.microsoft.com/pt-br/',
    license: 'freemium',
    color: '#5C2D91',
    popularity: 81,
    updatedDaysAgo: 4,
    tags: ['ide', '.net', 'c#', 'c++', 'microsoft'],
    oss: ['windows'],
    archs: ['x64'],
    alternatives: ['visual-studio-code'],
    packages: [W('Microsoft.VisualStudio.2022.Community')]
  }),
  a({
    slug: 'git',
    name: 'Git',
    vendor: 'Software Freedom Conservancy',
    categorySlug: 'desenvolvimento',
    tagline: 'Sistema de controle de versão essencial.',
    description:
      'O sistema de controle de versão distribuído mais usado do mundo. Base de qualquer fluxo de trabalho de desenvolvimento moderno.',
    websiteUrl: 'https://git-scm.com/',
    license: 'open_source',
    color: '#F05033',
    popularity: 97,
    updatedDaysAgo: 8,
    tags: ['controle de versão', 'vcs', 'github', 'desenvolvimento'],
    oss: ['windows', 'macos', 'linux'],
    archs: ['x64', 'arm64'],
    alternatives: [],
    packages: [
      W('Git.Git'),
      BF('git'),
      AP('git'),
      DN('git'),
      PC('git'),
      DL('https://git-scm.com/downloads', 'linux')
    ]
  }),
  a({
    slug: 'github-desktop',
    name: 'GitHub Desktop',
    vendor: 'GitHub',
    categorySlug: 'desenvolvimento',
    tagline: 'Interface gráfica simples para Git e GitHub.',
    description:
      'Cliente visual oficial do GitHub para commits, branches e pull requests sem linha de comando. Ótimo para quem está começando com Git.',
    websiteUrl: 'https://desktop.github.com/',
    license: 'open_source',
    color: '#8250DF',
    popularity: 73,
    updatedDaysAgo: 7,
    tags: ['git', 'github', 'interface gráfica'],
    oss: ['windows', 'macos'],
    archs: ['x64', 'arm64'],
    alternatives: [],
    packages: [W('GitHub.GitHubDesktop'), BC('github')]
  }),
  a({
    slug: 'notepad-plus-plus',
    name: 'Notepad++',
    vendor: 'Don Ho',
    categorySlug: 'desenvolvimento',
    tagline: 'Editor de texto leve para Windows.',
    description:
      'Editor de texto e código fonte rápido e leve, com realce de sintaxe para dezenas de linguagens, macros e busca em arquivos.',
    websiteUrl: 'https://notepad-plus-plus.org/',
    license: 'open_source',
    color: '#90E364',
    popularity: 71,
    updatedDaysAgo: 11,
    tags: ['editor de texto', 'leve', 'notas rápidas'],
    oss: ['windows'],
    archs: ['x64'],
    alternatives: [],
    packages: [W('Notepad++.Notepad++')]
  }),
  a({
    slug: 'windows-terminal',
    name: 'Windows Terminal',
    vendor: 'Microsoft',
    categorySlug: 'terminal',
    tagline: 'Terminal moderno para Windows com abas e perfis.',
    description:
      'Terminal da Microsoft com abas, painéis, perfis para PowerShell/CMD/WSL, GPU acceleration e temas. Substitui o console clássico.',
    websiteUrl: 'https://learn.microsoft.com/windows/terminal/',
    license: 'open_source',
    color: '#4A90D9',
    popularity: 74,
    updatedDaysAgo: 5,
    tags: ['terminal', 'shell', 'powershell', 'wsl'],
    oss: ['windows'],
    archs: ['x64', 'arm64'],
    alternatives: [],
    packages: [W('Microsoft.WindowsTerminal')]
  }),
  a({
    slug: 'powershell',
    name: 'PowerShell',
    vendor: 'Microsoft',
    categorySlug: 'terminal',
    tagline: 'Shell e automação multiplataforma da Microsoft.',
    description:
      'PowerShell 7 (Core), shell moderno multiplataforma com objetos na pipeline, scripting robusto e módulos para automação.',
    websiteUrl: 'https://learn.microsoft.com/powershell/',
    license: 'open_source',
    color: '#5391FE',
    popularity: 69,
    updatedDaysAgo: 6,
    tags: ['shell', 'automação', 'scripts', 'sysadmin'],
    oss: ['windows', 'macos', 'linux'],
    archs: ['x64', 'arm64'],
    alternatives: [],
    packages: [
      W('Microsoft.PowerShell'),
      BF('powershell'),
      DL('https://github.com/PowerShell/PowerShell/releases', 'linux')
    ]
  }),
  a({
    slug: 'docker-desktop',
    name: 'Docker Desktop',
    vendor: 'Docker Inc.',
    categorySlug: 'devops',
    tagline: 'Containers Docker com interface gráfica.',
    description:
      'Aplicativo oficial do Docker para Windows e macOS com engine, CLI, Compose e Kubernetes opcionais em uma instalação única.',
    websiteUrl: 'https://www.docker.com/products/docker-desktop/',
    license: 'freemium',
    color: '#2496ED',
    popularity: 86,
    updatedDaysAgo: 3,
    tags: ['containers', 'docker', 'devops', 'kubernetes'],
    oss: ['windows', 'macos', 'linux'],
    archs: ['x64', 'arm64'],
    alternatives: [],
    packages: [
      W('Docker.DockerDesktop'),
      BC('docker-desktop'),
      DL('https://docs.docker.com/engine/install/', 'linux')
    ]
  }),
  a({
    slug: 'postman',
    name: 'Postman',
    vendor: 'Postman Inc.',
    categorySlug: 'desenvolvimento',
    tagline: 'Plataforma para testar e documentar APIs.',
    description:
      'Cliente HTTP completo para testar APIs REST e GraphQL, criar coleções, ambientes, testes automatizados e documentação.',
    websiteUrl: 'https://www.postman.com/',
    license: 'freemium',
    color: '#FF6C37',
    popularity: 84,
    updatedDaysAgo: 4,
    tags: ['api', 'rest', 'graphql', 'http client'],
    oss: ['windows', 'macos', 'linux'],
    archs: ['x64', 'arm64'],
    alternatives: ['insomnia'],
    packages: [
      W('Postman.Postman'),
      BC('postman'),
      FP('com.getpostman.Postman', { source: 'official' }),
      SN('postman'),
      DL('https://www.postman.com/downloads/', 'linux')
    ]
  }),
  a({
    slug: 'insomnia',
    name: 'Insomnia',
    vendor: 'Kong',
    categorySlug: 'desenvolvimento',
    tagline: 'Cliente de APIs rápido e minimalista.',
    description:
      'Cliente HTTP para design, debug e teste de APIs REST e GraphQL, com interface limpa e suporte a gRPC.',
    websiteUrl: 'https://insomnia.rest/',
    license: 'open_source',
    color: '#660099',
    popularity: 63,
    updatedDaysAgo: 5,
    tags: ['api', 'rest', 'graphql', 'http client'],
    oss: ['windows', 'macos', 'linux'],
    archs: ['x64', 'arm64'],
    alternatives: ['postman'],
    packages: [
      W('Insomnia.Insomnia'),
      BC('insomnia'),
      FP('rest.insomnia.Insomnia', { source: 'community' })
    ]
  }),
  a({
    slug: 'dbeaver-ce',
    name: 'DBeaver Community',
    vendor: 'DBeaver Corp',
    categorySlug: 'banco-de-dados',
    tagline: 'Cliente universal de bancos de dados.',
    description:
      'Ferramenta gráfica open source para administrar PostgreSQL, MySQL, SQL Server, SQLite, Oracle e mais, com editor SQL avançado e modelagem ER.',
    websiteUrl: 'https://dbeaver.io/',
    license: 'open_source',
    color: '#C65D21',
    popularity: 72,
    updatedDaysAgo: 9,
    tags: ['banco de dados', 'sql', 'postgresql', 'mysql'],
    oss: ['windows', 'macos', 'linux'],
    archs: ['x64', 'arm64'],
    alternatives: [],
    packages: [
      W('DBeaver.DBeaver'),
      BC('dbeaver-community'),
      FP('io.dbeaver.DBeaverCommunity', { source: 'official' }),
      SN('dbeaver-ce'),
      PC('dbeaver'),
      DL('https://dbeaver.io/download/', 'linux')
    ]
  }),
  a({
    slug: 'nodejs',
    name: 'Node.js LTS',
    vendor: 'OpenJS Foundation',
    categorySlug: 'runtimes',
    tagline: 'Runtime JavaScript fora do navegador.',
    description:
      'Runtime JavaScript baseado no motor V8 com npm embutido. Essencial para desenvolvimento web fullstack, ferramentas CLIs e scripts.',
    websiteUrl: 'https://nodejs.org/',
    license: 'open_source',
    color: '#5FA04E',
    popularity: 92,
    updatedDaysAgo: 4,
    tags: ['javascript', 'runtime', 'npm', 'backend'],
    oss: ['windows', 'macos', 'linux'],
    archs: ['x64', 'arm64'],
    alternatives: [],
    packages: [
      W('OpenJS.NodeJS.LTS'),
      BF('node'),
      AP('nodejs', { notes: 'Versão dos repositórios; para versões recentes prefira nvm.' }),
      DN('nodejs'),
      PC('nodejs'),
      DL('https://nodejs.org/en/download', 'linux')
    ]
  }),
  a({
    slug: 'python',
    name: 'Python 3',
    vendor: 'Python Software Foundation',
    categorySlug: 'runtimes',
    tagline: 'Linguagem versátil para scripts, dados e backend.',
    description:
      'Interpreter Python 3 com pip. Usado de automações a ciência de dados, IA e desenvolvimento web. Em Linux/macOS já costuma vir instalado.',
    websiteUrl: 'https://www.python.org/',
    license: 'open_source',
    color: '#3776AB',
    popularity: 94,
    updatedDaysAgo: 10,
    tags: ['python', 'linguagem', 'pip', 'dados', 'ia'],
    oss: ['windows', 'macos', 'linux'],
    archs: ['x64', 'arm64'],
    alternatives: [],
    packages: [
      W('Python.Python.3.12'),
      BF('python@3.12'),
      AP('python3', { notes: 'Instala python3 + pip da distribuição.' }),
      DN('python3'),
      PC('python'),
      DL('https://www.python.org/downloads/', 'linux')
    ]
  }),
  a({
    slug: 'temurin-jdk21',
    name: 'Eclipse Temurin JDK 21',
    vendor: 'Eclipse Foundation',
    categorySlug: 'runtimes',
    tagline: 'OpenJDK gratuito com suporte de longo prazo.',
    description:
      'Distribuição OpenJDK 21 LTS mantida pelo Eclipse Adoptium, referência para rodar aplicações Java sem custos de licença.',
    websiteUrl: 'https://adoptium.net/',
    license: 'open_source',
    color: '#F37167',
    popularity: 67,
    updatedDaysAgo: 13,
    tags: ['java', 'jdk', 'jvm', 'lts'],
    oss: ['windows', 'macos', 'linux'],
    archs: ['x64', 'arm64'],
    alternatives: [],
    packages: [
      W('EclipseAdoptium.Temurin.21.JDK'),
      BC('temurin@21'),
      AP('default-jdk', { notes: 'OpenJDK padrão da distribuição.' }),
      DN('java-21-openjdk'),
      PC('jdk21-openjdk'),
      DL('https://adoptium.net/temurin/releases/', 'linux')
    ]
  }),
  a({
    slug: 'dotnet-sdk-8',
    name: '.NET SDK 8',
    vendor: 'Microsoft',
    categorySlug: 'runtimes',
    tagline: 'SDK para construir apps .NET modernos.',
    description:
      'Kit de desenvolvimento .NET 8 LTS com CLI dotnet, runtime ASP.NET Core e bibliotecas para web, desktop, mobile e cloud.',
    websiteUrl: 'https://dotnet.microsoft.com/',
    license: 'open_source',
    color: '#512BD4',
    popularity: 78,
    updatedDaysAgo: 12,
    tags: ['.net', 'c#', 'f#', 'microsoft', 'lts'],
    oss: ['windows', 'macos', 'linux'],
    archs: ['x64', 'arm64'],
    alternatives: [],
    packages: [
      W('Microsoft.DotNet.SDK.8'),
      BC('dotnet-sdk'),
      DL('https://dotnet.microsoft.com/en-us/download/dotnet/8.0', 'linux')
    ]
  }),
  a({
    slug: 'ollama',
    name: 'Ollama',
    vendor: 'Ollama',
    categorySlug: 'ia',
    tagline: 'Rode LLMs localmente com um comando.',
    description:
      'Ferramenta para baixar e executar modelos de linguagem abertos (Llama, Gemma, Mistral) localmente via API e terminal.',
    websiteUrl: 'https://ollama.com/',
    license: 'open_source',
    color: '#111113',
    popularity: 71,
    updatedDaysAgo: 1,
    tags: ['ia', 'llm', 'local', 'modelos'],
    oss: ['windows', 'macos', 'linux'],
    archs: ['x64', 'arm64'],
    alternatives: [],
    packages: [
      W('Ollama.Ollama'),
      BF('ollama'),
      DL('https://ollama.com/download', 'linux')
    ]
  }),
  a({
    slug: 'steam',
    name: 'Steam',
    vendor: 'Valve',
    categorySlug: 'gaming',
    tagline: 'A maior loja e plataforma de jogos do PC.',
    description:
      'Plataforma da Valve para comprar, instalar e jogar jogos, com Proton no Linux para executar títulos de Windows, Steam Remote Play e Workshop.',
    websiteUrl: 'https://store.steampowered.com/',
    license: 'freeware',
    color: '#66C0F4',
    popularity: 91,
    updatedDaysAgo: 2,
    tags: ['jogos', 'gaming', 'valve', 'proton'],
    oss: ['windows', 'macos', 'linux'],
    archs: ['x64'],
    alternatives: [],
    packages: [
      W('Valve.Steam'),
      BC('steam'),
      FP('com.valvesoftware.Steam', { source: 'official' }),
      AP('steam-installer', { notes: 'Requer habilitar repositório multiverse.' }),
      PC('steam', { repository: 'multilib', notes: 'Requer multilib habilitado no pacman.conf.' })
    ]
  }),
  a({
    slug: 'epic-games-launcher',
    name: 'Epic Games Launcher',
    vendor: 'Epic Games',
    categorySlug: 'gaming',
    tagline: 'Loja Epic com jogos grátis semanais.',
    description:
      'Launcher da Epic Games com catálogo, jogos gratuitos semanais e Fortnite. Disponível apenas para Windows.',
    websiteUrl: 'https://store.epicgames.com/',
    license: 'freeware',
    color: '#313131',
    popularity: 76,
    updatedDaysAgo: 3,
    tags: ['jogos', 'epic', 'fortnite'],
    oss: ['windows'],
    archs: ['x64'],
    alternatives: [],
    packages: [W('EpicGames.EpicGamesLauncher')]
  }),
  a({
    slug: 'qbittorrent',
    name: 'qBittorrent',
    vendor: 'qBittorrent Team',
    categorySlug: 'internet',
    tagline: 'Cliente torrent leve, livre e sem anúncios.',
    description:
      'Cliente BitTorrent open source com busca integrada, gerenciamento de velocidade, RSS e interface web opcional.',
    websiteUrl: 'https://www.qbittorrent.org/',
    license: 'open_source',
    color: '#35A0D4',
    popularity: 65,
    updatedDaysAgo: 8,
    tags: ['torrent', 'p2p', 'downloads'],
    oss: ['windows', 'macos', 'linux'],
    archs: ['x64'],
    alternatives: [],
    packages: [
      W('qBittorrent.qBittorrent'),
      BC('qbittorrent'),
      FP('org.qbittorrent.qBittorrent', { source: 'official' }),
      AP('qbittorrent'),
      DN('qbittorrent'),
      PC('qbittorrent')
    ]
  }),
  a({
    slug: 'filezilla',
    name: 'FileZilla',
    vendor: 'FileZilla Foundation',
    categorySlug: 'internet',
    tagline: 'Transferência FTP/SFTP confiável.',
    description:
      'Cliente FTP clássico com gerenciador de sites, transferências simultâneas, SFTP e FTPS. Padrão para publicar arquivos em servidores.',
    websiteUrl: 'https://filezilla-project.org/',
    license: 'open_source',
    color: '#BF0000',
    popularity: 59,
    updatedDaysAgo: 16,
    tags: ['ftp', 'sftp', 'transferência'],
    oss: ['windows', 'macos', 'linux'],
    archs: ['x64'],
    alternatives: ['winscp'],
    packages: [
      OI('https://filezilla-project.org/download.php?type=client', 'macos'),
      FP('org.filezillaproject.Filezilla', { source: 'official' }),
      AP('filezilla'),
      DN('filezilla'),
      PC('filezilla')
    ]
  }),
  a({
    slug: '7zip',
    name: '7-Zip',
    vendor: 'Igor Pavlov',
    categorySlug: 'compactacao',
    tagline: 'Compactador gratuito com alta compressão.',
    description:
      'Arquivador open source com taxa de compressão excelente no formato 7z e suporte a ZIP, RAR (extração), TAR e mais. Integrado ao menu do Explorer.',
    websiteUrl: 'https://www.7-zip.org/',
    license: 'open_source',
    color: '#7B87DA',
    popularity: 96,
    updatedDaysAgo: 25,
    tags: ['compactador', 'zip', 'rar', '7z', 'winrar alternativa'],
    oss: ['windows', 'linux'],
    archs: ['x64', 'arm64'],
    alternatives: ['peazip', 'nanazip'],
    packages: [
      W('7zip.7zip'),
      AP('p7zip-full', { notes: 'Fornece os comandos 7z e 7za.' }),
      DN('p7zip', { notes: 'Inclua p7zip-plugins para mais formatos.' }),
      PC('p7zip')
    ]
  }),
  a({
    slug: 'peazip',
    name: 'PeaZip',
    vendor: 'Giorgio Tani',
    categorySlug: 'compactacao',
    tagline: 'Arquivador com interface gráfica completa.',
    description:
      'Compactador open source com suporte a 200+ formatos, criptografia AES, divisão de arquivos e testes de integridade.',
    websiteUrl: 'https://peazip.github.io/',
    license: 'open_source',
    color: '#F68212',
    popularity: 48,
    updatedDaysAgo: 22,
    tags: ['compactador', 'zip', 'criptografia'],
    oss: ['windows', 'linux'],
    archs: ['x64'],
    alternatives: ['7zip', 'nanazip'],
    packages: [
      W('Giorgiotani.Peazip'),
      FP('io.github.peazip.PeaZip'),
      DL('https://peazip.github.io/peazip-linux.html', 'linux')
    ]
  }),
  a({
    slug: 'nanazip',
    name: 'NanaZip',
    vendor: 'Kenji Mouri',
    categorySlug: 'compactacao',
    tagline: 'Fork moderno do 7-Zip para Windows 11.',
    description:
      'Fork do 7-Zip empacotado como aplicativo MSIX, com menu de contexto do Windows 11 e tema escuro. Mantido pela comunidade M2Team.',
    websiteUrl: 'https://github.com/M2Team/NanaZip',
    license: 'open_source',
    color: '#10893E',
    popularity: 45,
    updatedDaysAgo: 14,
    tags: ['compactador', 'windows 11', 'msix'],
    oss: ['windows'],
    archs: ['x64', 'arm64'],
    alternatives: ['7zip', 'peazip'],
    packages: [W('M2Team.NanaZip')]
  }),
  a({
    slug: 'everything',
    name: 'Everything',
    vendor: 'voidtools',
    categorySlug: 'utilitarios',
    tagline: 'Busca instantânea de arquivos por nome.',
    description:
      'Utilitário que indexa o NTFS em tempo real e encontra qualquer arquivo no Windows enquanto você digita. Extremamente rápido e leve.',
    websiteUrl: 'https://www.voidtools.com/',
    license: 'freeware',
    color: '#6666CC',
    popularity: 62,
    updatedDaysAgo: 30,
    tags: ['busca', 'arquivos', 'produtividade'],
    oss: ['windows'],
    archs: ['x64'],
    alternatives: [],
    packages: [W('voidtools.Everything')]
  }),
  a({
    slug: 'powertoys',
    name: 'PowerToys',
    vendor: 'Microsoft',
    categorySlug: 'utilitarios',
    tagline: 'Coleção de utilitários avançados para Windows.',
    description:
      'Suíte da Microsoft com FancyZones, PowerRename, Color Picker, File Locksmith, Keyboard Manager e dezenas de outras ferramentas.',
    websiteUrl: 'https://learn.microsoft.com/windows/powertoys/',
    license: 'open_source',
    color: '#744DA9',
    popularity: 82,
    updatedDaysAgo: 2,
    tags: ['produtividade', 'windows', 'microsoft', 'fancyzones'],
    oss: ['windows'],
    archs: ['x64', 'arm64'],
    alternatives: [],
    packages: [W('Microsoft.PowerToys')]
  }),
  a({
    slug: 'sharex',
    name: 'ShareX',
    vendor: 'ShareX Team',
    categorySlug: 'utilitarios',
    tagline: 'Capturas de tela e gravação com workflows.',
    description:
      'Ferramenta open source de captura de tela, gravadora, OCR e upload automático para dezenas de destinos, com atalhos personalizáveis.',
    websiteUrl: 'https://getsharex.com/',
    license: 'open_source',
    color: '#0EA5E9',
    popularity: 60,
    updatedDaysAgo: 9,
    tags: ['captura de tela', 'screenshot', 'ocr'],
    oss: ['windows'],
    archs: ['x64'],
    alternatives: [],
    packages: [W('ShareX.ShareX')]
  }),
  a({
    slug: 'sumatrapdf',
    name: 'Sumatra PDF',
    vendor: 'Krzysztof Kowalczyk',
    categorySlug: 'pdf',
    tagline: 'Leitor de PDF ultraleve e rápido.',
    description:
      'Leitor de PDF, EPUB, MOBI e quadrinhos extremamente leve, abre instantaneamente e consome pouquíssimos recursos.',
    websiteUrl: 'https://www.sumatrapdfreader.org/',
    license: 'open_source',
    color: '#8F8F8F',
    popularity: 55,
    updatedDaysAgo: 18,
    tags: ['pdf', 'leitor', 'leve'],
    oss: ['windows'],
    archs: ['x64'],
    alternatives: ['adobe-acrobat-reader'],
    packages: [W('SumatraPDF.SumatraPDF')]
  }),
  a({
    slug: 'adobe-acrobat-reader',
    name: 'Adobe Acrobat Reader',
    vendor: 'Adobe',
    categorySlug: 'pdf',
    tagline: 'Leitor de PDF padrão do mercado.',
    description:
      'Leitor oficial da Adobe com comentários, preenchimento de formulários e assinaturas digitais. Necessário em muitos fluxos corporativos.',
    websiteUrl: 'https://get.adobe.com/reader/',
    license: 'freeware',
    color: '#EC1C24',
    popularity: 88,
    updatedDaysAgo: 5,
    tags: ['pdf', 'adobe', 'formulários'],
    oss: ['windows', 'macos'],
    archs: ['x64'],
    alternatives: ['sumatrapdf'],
    packages: [W('Adobe.Acrobat.Reader.64-bit'), BC('adobe-acrobat-reader')]
  }),
  a({
    slug: 'rufus',
    name: 'Rufus',
    vendor: 'Pete Batard',
    categorySlug: 'utilitarios',
    tagline: 'Criador de pendrives bootáveis rápido.',
    description:
      'Utilitário para criar unidades USB bootáveis de ISOs do Windows e Linux, incluindo bypass de requisitos do Windows 11.',
    websiteUrl: 'https://rufus.ie/',
    license: 'open_source',
    color: '#E05A2B',
    popularity: 68,
    updatedDaysAgo: 20,
    tags: ['bootável', 'usb', 'iso', 'instalação'],
    oss: ['windows'],
    archs: ['x64'],
    alternatives: ['balena-etcher'],
    packages: [W('Rufus.Rufus')]
  }),
  a({
    slug: 'balena-etcher',
    name: 'balenaEtcher',
    vendor: 'balena.io',
    categorySlug: 'utilitarios',
    tagline: 'Gravador de imagens em USB com 3 cliques.',
    description:
      'Ferramenta simples e visual para gravar ISOs em cartões SD e pendrives, validando a gravação ao final. Multiplataforma.',
    websiteUrl: 'https://etcher.balena.io/',
    license: 'open_source',
    color: '#009FE3',
    popularity: 58,
    updatedDaysAgo: 24,
    tags: ['bootável', 'usb', 'sd card', 'iso'],
    oss: ['windows', 'macos', 'linux'],
    archs: ['x64', 'arm64'],
    alternatives: ['rufus'],
    packages: [
      W('Balena.Etcher'),
      BC('balenaetcher'),
      DL('https://github.com/balena-io/etcher/releases/latest', 'linux')
    ]
  }),
  a({
    slug: 'crystaldiskinfo',
    name: 'CrystalDiskInfo',
    vendor: 'Crystal Dew World',
    categorySlug: 'hardware',
    tagline: 'Saúde e temperatura de discos via SMART.',
    description:
      'Monitora saúde HD/SSD com dados SMART, temperatura, horas ligado e setores ruins. Essencial para diagnosticar falhas de armazenamento.',
    websiteUrl: 'https://crystalmark.info/',
    license: 'open_source',
    color: '#6BA7D6',
    popularity: 57,
    updatedDaysAgo: 26,
    tags: ['hardware', 'disco', 'ssd', 'smart', 'diagnóstico'],
    oss: ['windows'],
    archs: ['x64'],
    alternatives: [],
    packages: [W('CrystalDewWorld.CrystalDiskInfo')]
  }),
  a({
    slug: 'cpu-z',
    name: 'CPU-Z',
    vendor: 'CPUID',
    categorySlug: 'hardware',
    tagline: 'Informações detalhadas de CPU, RAM e placa-mãe.',
    description:
      'Identifica processador, memória, placa-mãe e GPU com precisão, incluindo benchmarks básicos. Clássico para conferir especificações reais.',
    websiteUrl: 'https://www.cpuid.com/softwares/cpu-z.html',
    license: 'freeware',
    color: '#4A90D9',
    popularity: 61,
    updatedDaysAgo: 28,
    tags: ['hardware', 'cpu', 'memória', 'diagnóstico'],
    oss: ['windows'],
    archs: ['x64'],
    alternatives: [],
    packages: [W('CPUID.CPU-Z')]
  }),
  a({
    slug: 'hwinfo',
    name: 'HWiNFO',
    vendor: 'REALiX',
    categorySlug: 'hardware',
    tagline: 'Monitoramento profundo de sensores do sistema.',
    description:
      'Monitor completo de temperaturas, voltagens, frequências e consumo, com logs e alertas. Referência para diagnóstico térmico.',
    websiteUrl: 'https://www.hwinfo.com/',
    license: 'freeware',
    color: '#D64545',
    popularity: 54,
    updatedDaysAgo: 12,
    tags: ['hardware', 'sensores', 'temperatura', 'monitoramento'],
    oss: ['windows'],
    archs: ['x64'],
    alternatives: [],
    packages: [W('REALiX.HWiNFO')]
  }),
  a({
    slug: 'virtualbox',
    name: 'VirtualBox',
    vendor: 'Oracle',
    categorySlug: 'virtualizacao',
    tagline: 'Virtualizador gratuito multiplataforma.',
    description:
      'Hipervisor tipo 2 open source para rodar VMs Windows/Linux no desktop, com snapshots, pastas compartilhadas e Guest Additions.',
    websiteUrl: 'https://www.virtualbox.org/',
    license: 'open_source',
    color: '#183A7B',
    popularity: 66,
    updatedDaysAgo: 17,
    tags: ['virtualização', 'vm', 'máquina virtual', 'oracle'],
    oss: ['windows', 'macos', 'linux'],
    archs: ['x64'],
    alternatives: [],
    packages: [
      W('Oracle.VirtualBox'),
      BC('virtualbox'),
      AP('virtualbox', { notes: 'Pode exigir habilitar repositório contrib.' }),
      DL('https://www.virtualbox.org/wiki/Linux_Downloads', 'linux')
    ]
  }),
  a({
    slug: 'putty',
    name: 'PuTTY',
    vendor: 'Simon Tatham',
    categorySlug: 'sysadmin',
    tagline: 'Cliente SSH e Telnet clássico para Windows.',
    description:
      'Cliente SSH/Telnet/serial leve com gerenciador de sessões, túneis e autenticação por chave. Ferramenta básica de administração remota.',
    websiteUrl: 'https://www.putty.org/',
    license: 'open_source',
    color: '#D9C33C',
    popularity: 70,
    updatedDaysAgo: 33,
    tags: ['ssh', 'telnet', 'remote', 'sysadmin'],
    oss: ['windows'],
    archs: ['x64'],
    alternatives: [],
    packages: [W('PuTTY.PuTTY')]
  }),
  a({
    slug: 'winscp',
    name: 'WinSCP',
    vendor: 'Martin Prikryl',
    categorySlug: 'sysadmin',
    tagline: 'Transferência SFTP/SCP com interface dupla.',
    description:
      'Cliente gráfico SFTP, SCP, FTP e S3 para Windows com sincronização de diretórios, editor integrado e automação via script .NET.',
    websiteUrl: 'https://winscp.net/',
    license: 'open_source',
    color: '#1E6EC8',
    popularity: 64,
    updatedDaysAgo: 15,
    tags: ['sftp', 'scp', 'ftp', 'sysadmin', 'transferência'],
    oss: ['windows'],
    archs: ['x64'],
    alternatives: ['filezilla'],
    packages: [W('WinSCP.WinSCP')]
  }),
  a({
    slug: 'wireshark',
    name: 'Wireshark',
    vendor: 'Wireshark Foundation',
    categorySlug: 'sysadmin',
    tagline: 'Analisador de tráfego de rede definitivo.',
    description:
      'Captura e inspeciona pacotes de rede com filtros poderosos, decodificação de centenas de protocolos e estatísticas detalhadas.',
    websiteUrl: 'https://www.wireshark.org/',
    license: 'open_source',
    color: '#1679A7',
    popularity: 73,
    updatedDaysAgo: 7,
    tags: ['rede', 'análise', 'pacotes', 'debug', 'sysadmin'],
    oss: ['windows', 'macos', 'linux'],
    archs: ['x64', 'arm64'],
    alternatives: [],
    packages: [
      W('WiresharkFoundation.Wireshark'),
      BC('wireshark-app'),
      AP('wireshark'),
      DN('wireshark'),
      PC('wireshark-qt')
    ]
  }),
  a({
    slug: 'nmap',
    name: 'Nmap',
    vendor: 'Nmap Project',
    categorySlug: 'sysadmin',
    tagline: 'Scanner de rede e portas essencial.',
    description:
      'Descobre hosts, portas abertas, serviços e sistemas operacionais em redes. Inclui Zenmap (GUI), NSE scripts e ferramentas auxiliares.',
    websiteUrl: 'https://nmap.org/',
    license: 'open_source',
    color: '#6B4FA0',
    popularity: 68,
    updatedDaysAgo: 19,
    tags: ['rede', 'scanner', 'segurança', 'sysadmin'],
    oss: ['windows', 'macos', 'linux'],
    archs: ['x64', 'arm64'],
    alternatives: [],
    packages: [W('Insecure.Nmap'), BF('nmap'), AP('nmap'), DN('nmap'), PC('nmap')]
  }),
  a({
    slug: 'process-explorer',
    name: 'Process Explorer',
    vendor: 'Microsoft Sysinternals',
    categorySlug: 'sysadmin',
    tagline: 'Gerenciador de tarefas avançado da Microsoft.',
    description:
      'Mostra árvores de processos, handles, DLLs carregadas e assinaturas digitais. Substitui o Gerenciador de Tarefas em diagnósticos.',
    websiteUrl: 'https://learn.microsoft.com/sysinternals/downloads/process-explorer',
    license: 'freeware',
    color: '#0078D4',
    popularity: 53,
    updatedDaysAgo: 35,
    tags: ['processos', 'sysinternals', 'diagnóstico', 'windows'],
    oss: ['windows'],
    archs: ['x64'],
    alternatives: [],
    packages: [W('Microsoft.Sysinternals.ProcessExplorer')]
  }),
  a({
    slug: 'rustdesk',
    name: 'RustDesk',
    vendor: 'RustDesk',
    categorySlug: 'sysadmin',
    tagline: 'Acesso remoto open source estilo AnyDesk.',
    description:
      'Controle remoto de desktop com criptografia ponta a ponta, servidor próprio opcional e clientes para todas as plataformas.',
    websiteUrl: 'https://rustdesk.com/',
    license: 'open_source',
    color: '#2E5BFF',
    popularity: 56,
    updatedDaysAgo: 6,
    tags: ['acesso remoto', 'suporte', 'teamviewer alternativa'],
    oss: ['windows', 'macos', 'linux'],
    archs: ['x64', 'arm64'],
    alternatives: ['anydesk'],
    packages: [
      OI('https://github.com/rustdesk/rustdesk/releases/latest', 'windows'),
      FP('com.rustdesk.RustDesk'),
      DL('https://github.com/rustdesk/rustdesk/releases/latest', 'linux')
    ]
  }),
  a({
    slug: 'anydesk',
    name: 'AnyDesk',
    vendor: 'AnyDesk Software GmbH',
    categorySlug: 'sysadmin',
    tagline: 'Acesso remoto leve e rápido.',
    description:
      'Acesso remoto proprietário conhecido pela baixa latência, usado amplamente por técnicos para atendimento a distância.',
    websiteUrl: 'https://anydesk.com/pt',
    license: 'freemium',
    color: '#E0393E',
    popularity: 67,
    updatedDaysAgo: 8,
    tags: ['acesso remoto', 'suporte', 'técnico'],
    oss: ['windows', 'macos', 'linux'],
    archs: ['x64'],
    alternatives: ['rustdesk'],
    packages: [
      W('AnyDesk.AnyDesk'),
      DL('https://anydesk.com/pt/downloads/linux', 'linux')
    ]
  }),
  a({
    slug: 'veracrypt',
    name: 'VeraCrypt',
    vendor: 'IDRIX',
    categorySlug: 'seguranca',
    tagline: 'Criptografia de discos e volumes.',
    description:
      'Sucessor do TrueCrypt para criar volumes criptografados e criptografar partições inteiras com AES/Twofish/Serpent.',
    websiteUrl: 'https://www.veracrypt.fr/',
    license: 'open_source',
    color: '#5064A0',
    popularity: 52,
    updatedDaysAgo: 21,
    tags: ['criptografia', 'disco', 'privacidade', 'segurança'],
    oss: ['windows', 'macos', 'linux'],
    archs: ['x64'],
    alternatives: [],
    packages: [
      W('IDRIX.VeraCrypt'),
      BC('veracrypt'),
      PC('veracrypt'),
      DL('https://www.veracrypt.fr/en/Downloads.html', 'linux')
    ]
  }),
  a({
    slug: 'cryptomator',
    name: 'Cryptomator',
    vendor: 'Skymatic GmbH',
    categorySlug: 'seguranca',
    tagline: 'Criptografe pastas na nuvem facilmente.',
    description:
      'Criptografia transparente para Dropbox, Google Drive, OneDrive e afins, criando cofres virtuais compatíveis entre dispositivos.',
    websiteUrl: 'https://cryptomator.org/',
    license: 'open_source',
    color: '#3CB56B',
    popularity: 49,
    updatedDaysAgo: 13,
    tags: ['criptografia', 'nuvem', 'privacidade'],
    oss: ['windows', 'macos', 'linux'],
    archs: ['x64', 'arm64'],
    alternatives: [],
    packages: [
      W('Cryptomator.Cryptomator'),
      BC('cryptomator'),
      FP('org.cryptomator.Cryptomator', { source: 'official' })
    ]
  }),
  a({
    slug: 'anki',
    name: 'Anki',
    vendor: 'Anki',
    categorySlug: 'educacao',
    tagline: 'Flashcards com repetição espaçada.',
    description:
      'Programa de memorização com repetição espaçada usado em medicina, idiomas e concursos. Sincroniza decks entre dispositivos.',
    websiteUrl: 'https://apps.ankiweb.net/',
    license: 'open_source',
    color: '#6CA9E8',
    popularity: 51,
    updatedDaysAgo: 11,
    tags: ['estudos', 'flashcards', 'memorização', 'concurso'],
    oss: ['windows', 'macos', 'linux'],
    archs: ['x64'],
    alternatives: [],
    packages: [
      W('Anki.Anki'),
      BC('anki'),
      FP('net.ankiweb.Anki', { source: 'official' })
    ]
  })
];
