import type { CatalogApp } from './types';
import { AP, BC, DL, DN, PC, W } from './types';

const a = (
  base: Omit<CatalogApp, 'iconKey' | 'status' | 'version'> & Partial<Pick<CatalogApp, 'iconKey' | 'status' | 'version'>>
): CatalogApp => ({
  iconKey: base.slug,
  status: 'verified',
  version: null,
  ...base
});

export const appsG: CatalogApp[] = [
  // ---------------------------------------------------------------- dependências
  a({
    slug: 'vc-redist-2015-2022-x64',
    name: 'Visual C++ Redistributable 2015-2022 (x64)',
    vendor: 'Microsoft',
    categorySlug: 'runtimes',
    tagline: 'Dependência obrigatória de jogos e programas modernos (64-bit).',
    description:
      'Bibliotecas de runtime do Visual C++ 2015 a 2022 para 64-bit. Jogos, utilitários e programas de terceiros exigem este pacote — sem ele aparecem erros como "VCRUNTIME140.dll não encontrado". Instale antes de rodar qualquer coisa após formatar.',
    websiteUrl: 'https://learn.microsoft.com/cpp/windows/latest-supported-vc-redist',
    license: 'freeware',
    color: '#5C2D91',
    popularity: 85,
    updatedDaysAgo: 5,
    tags: ['vc++', 'redistributable', 'dependencia', 'microsoft', 'runtime'],
    oss: ['windows'],
    archs: ['x64'],
    alternatives: ['vc-redist-2015-2022-x86'],
    packages: [W('Microsoft.VCRedist.2015+.x64')]
  }),
  a({
    slug: 'vc-redist-2015-2022-x86',
    name: 'Visual C++ Redistributable 2015-2022 (x86)',
    vendor: 'Microsoft',
    categorySlug: 'runtimes',
    tagline: 'Runtime do Visual C++ para programas de 32-bit.',
    description:
      'Versão 32-bit das bibliotecas do Visual C++ 2015-2022. Muitos aplicativos e jogos antigos são 32-bit e precisam desta versão mesmo em Windows 64-bit — o ideal é instalar as duas (x64 + x86).',
    websiteUrl: 'https://learn.microsoft.com/cpp/windows/latest-supported-vc-redist',
    license: 'freeware',
    color: '#5C2D91',
    popularity: 82,
    updatedDaysAgo: 5,
    tags: ['vc++', 'redistributable', 'dependencia', 'microsoft', 'runtime', 'x86'],
    oss: ['windows'],
    archs: ['x64'],
    alternatives: ['vc-redist-2015-2022-x64'],
    packages: [W('Microsoft.VCRedist.2015+.x86')]
  }),
  a({
    slug: 'vc-redist-2013-x64',
    name: 'Visual C++ Redistributable 2013 (x64)',
    vendor: 'Microsoft',
    categorySlug: 'runtimes',
    tagline: 'Runtime legado do Visual C++ 2013 para 64-bit.',
    description:
      'Necessário para programas compilados com Visual Studio 2013. Só instale se algum aplicativo específico reclamar de MSVCR120.dll — o pacote 2015-2022 não substitui esta versão.',
    websiteUrl: 'https://learn.microsoft.com/cpp/windows/latest-supported-vc-redist',
    license: 'freeware',
    color: '#5C2D91',
    popularity: 45,
    updatedDaysAgo: 30,
    tags: ['vc++', 'redistributable', 'dependencia', 'legado'],
    oss: ['windows'],
    archs: ['x64'],
    alternatives: [],
    packages: [W('Microsoft.VCRedist.2013.x64')]
  }),
  a({
    slug: 'vc-redist-2012-x64',
    name: 'Visual C++ Redistributable 2012 (x64)',
    vendor: 'Microsoft',
    categorySlug: 'runtimes',
    tagline: 'Runtime legado do Visual C++ 2012 para 64-bit.',
    description:
      'Para programas compilados com Visual Studio 2012 (erro típico: MSVCR110.dll). Comum em jogos e softwares corporativos antigos.',
    websiteUrl: 'https://learn.microsoft.com/cpp/windows/latest-supported-vc-redist',
    license: 'freeware',
    color: '#5C2D91',
    popularity: 48,
    updatedDaysAgo: 30,
    tags: ['vc++', 'redistributable', 'dependencia', 'legado'],
    oss: ['windows'],
    archs: ['x64'],
    alternatives: [],
    packages: [W('Microsoft.VCRedist.2012.x64')]
  }),
  a({
    slug: 'vc-redist-2010-x64',
    name: 'Visual C++ Redistributable 2010 (x64)',
    vendor: 'Microsoft',
    categorySlug: 'runtimes',
    tagline: 'Runtime legado do Visual C++ 2010 para 64-bit.',
    description:
      'Para programas muito antigos compilados com Visual Studio 2010 (erro típico: MSVCR100.dll). Instale apenas sob demanda.',
    websiteUrl: 'https://learn.microsoft.com/cpp/windows/latest-supported-vc-redist',
    license: 'freeware',
    color: '#5C2D91',
    popularity: 42,
    updatedDaysAgo: 30,
    tags: ['vc++', 'redistributable', 'dependencia', 'legado'],
    oss: ['windows'],
    archs: ['x64'],
    alternatives: [],
    packages: [W('Microsoft.VCRedist.2010.x64')]
  }),
  a({
    slug: 'directx-end-user-runtime',
    name: 'DirectX End-User Runtime',
    vendor: 'Microsoft',
    categorySlug: 'runtimes',
    tagline: 'DLLs legadas do DirectX (D3DX9, XInput) exigidas por jogos.',
    description:
      'Instalador offline das bibliotecas legadas do DirectX 9.0c (d3dx9_xx.dll, XInput, D3DCompiler). Jogos mais antigos e emuladores pedem essas DLLs mesmo no Windows 11 — sem elas aparecem erros como "d3dx9_43.dll não encontrado". O DirectX 12 já vem no Windows; este pacote é só o legado.',
    websiteUrl: 'https://www.microsoft.com/pt-br/download/details.aspx?id=35',
    license: 'freeware',
    color: '#0078D4',
    popularity: 80,
    updatedDaysAgo: 60,
    tags: ['directx', 'jogos', 'dependencia', 'microsoft', 'runtime'],
    oss: ['windows'],
    archs: ['x64'],
    alternatives: [],
    packages: [W('Microsoft.DirectX')]
  }),
  a({
    slug: 'dotnet-desktop-runtime-8',
    name: '.NET Desktop Runtime 8',
    vendor: 'Microsoft',
    categorySlug: 'runtimes',
    tagline: 'Runtime para aplicativos WPF/WinForms (.NET 8 LTS).',
    description:
      'Permite executar programas de desktop .NET 8 (WPF e WinForms). Muitos aplicativos de terceiros pedem "Microsoft Windows Desktop Runtime" — este é o pacote. O SDK do .NET já o inclui; instale este apenas em máquinas que só rodam programas.',
    websiteUrl: 'https://dotnet.microsoft.com/download/dotnet/8.0',
    license: 'open_source',
    color: '#512BD4',
    popularity: 75,
    updatedDaysAgo: 4,
    tags: ['.net', 'dependencia', 'microsoft', 'runtime', 'lts', 'wpf'],
    oss: ['windows'],
    archs: ['x64', 'arm64'],
    alternatives: ['dotnet-desktop-runtime-10', 'dotnet-sdk-8'],
    packages: [W('Microsoft.DotNet.DesktopRuntime.8')]
  }),
  a({
    slug: 'dotnet-desktop-runtime-10',
    name: '.NET Desktop Runtime 10',
    vendor: 'Microsoft',
    categorySlug: 'runtimes',
    tagline: 'Runtime para aplicativos WPF/WinForms (.NET 10 LTS).',
    description:
      'Versão atual LTS do runtime de desktop do .NET, exigida por programas construídos em .NET 10. Instale junto com o runtime 8 para cobrir aplicativos de ambas as gerações.',
    websiteUrl: 'https://dotnet.microsoft.com/download/dotnet/10.0',
    license: 'open_source',
    color: '#512BD4',
    popularity: 68,
    updatedDaysAgo: 4,
    tags: ['.net', 'dependencia', 'microsoft', 'runtime', 'lts'],
    oss: ['windows'],
    archs: ['x64', 'arm64'],
    alternatives: ['dotnet-desktop-runtime-8'],
    packages: [W('Microsoft.DotNet.DesktopRuntime.10')]
  }),
  a({
    slug: 'dotnet-framework-481',
    name: '.NET Framework 4.8.1',
    vendor: 'Microsoft',
    categorySlug: 'runtimes',
    tagline: 'Framework clássico exigido por programas Windows antigos.',
    description:
      'O .NET Framework 4.8.1 já vem no Windows 11 e chega pelo Windows Update no Windows 10. Instale o instalador offline apenas se algum programa reclamar especificamente — programas corporativos e utilitários antigos dependem dele.',
    websiteUrl: 'https://dotnet.microsoft.com/pt-br/download/dotnet-framework/net481',
    license: 'freeware',
    color: '#3C80D1',
    popularity: 60,
    updatedDaysAgo: 90,
    tags: ['.net', 'framework', 'dependencia', 'microsoft', 'legado'],
    oss: ['windows'],
    archs: ['x64'],
    alternatives: [],
    packages: [DL('https://dotnet.microsoft.com/pt-br/download/dotnet-framework/net481', 'windows')]
  }),
  a({
    slug: 'corretto-jre8',
    name: 'Amazon Corretto JRE 8',
    vendor: 'Amazon',
    categorySlug: 'runtimes',
    tagline: 'Java 8 gratuito com suporte de longo prazo da Amazon.',
    description:
      'Distribuição gratuita do Java 8 (JRE) mantida pela Amazon. Sistemas legados — bancos, emissores de NF, aplicativos governamentais — frequentemente exigem Java 8 especificamente. Alternativa sem custo de licença ao Oracle Java.',
    websiteUrl: 'https://aws.amazon.com/corretto/',
    license: 'open_source',
    color: '#FF9900',
    popularity: 40,
    updatedDaysAgo: 15,
    tags: ['java', 'jre', 'jvm', 'legado', 'dependencia'],
    oss: ['windows'],
    archs: ['x64'],
    alternatives: ['temurin-jdk21'],
    packages: [W('Amazon.Corretto.8.JRE')]
  }),

  // ---------------------------------------------------------------- apps
  a({
    slug: 'mozilla-thunderbird',
    name: 'Thunderbird',
    vendor: 'Mozilla',
    categorySlug: 'comunicacao',
    tagline: 'Cliente de e-mail completo e open source.',
    description:
      'Cliente de e-mail, calendário e contatos da Mozilla. Suporta múltiplas contas POP/IMAP, criptografia OpenPGP nativa e calendário integrado. Alternativa clássica ao Outlook.',
    websiteUrl: 'https://www.thunderbird.net/pt-BR/',
    license: 'open_source',
    color: '#0A84FF',
    popularity: 62,
    updatedDaysAgo: 3,
    tags: ['email', 'mozilla', 'calendario', 'open source'],
    oss: ['windows', 'macos', 'linux'],
    archs: ['x64', 'arm64'],
    alternatives: [],
    packages: [
      W('Mozilla.Thunderbird'),
      BC('thunderbird'),
      AP('thunderbird'),
      DN('thunderbird'),
      PC('thunderbird'),
      DL('https://www.thunderbird.net/pt-BR/', 'linux')
    ]
  }),
  a({
    slug: 'itunes',
    name: 'iTunes',
    vendor: 'Apple',
    categorySlug: 'multimidia',
    tagline: 'Gerenciador de mídia e dispositivos Apple no Windows.',
    description:
      'Player e biblioteca de mídia da Apple. Ainda é a forma oficial de sincronizar iPhone/iPad mais antigos e fazer backup local no Windows.',
    websiteUrl: 'https://www.apple.com/br/itunes/',
    license: 'freeware',
    color: '#FA57C1',
    popularity: 55,
    updatedDaysAgo: 10,
    tags: ['apple', 'musica', 'iphone', 'midia'],
    oss: ['windows', 'macos'],
    archs: ['x64'],
    alternatives: [],
    packages: [W('Apple.iTunes'), BC('itunes')]
  }),
  a({
    slug: 'aimp',
    name: 'AIMP',
    vendor: 'AIMP DevTeam',
    categorySlug: 'audio',
    tagline: 'Player de áudio leve com equalizador de 18 bandas.',
    description:
      'Player de música russo, gratuito e muito leve. Suporta diversos formatos, equalizador avançado, conversão de áudio e biblioteca com abas — favorito de quem só quer ouvir música sem peso.',
    websiteUrl: 'https://www.aimp.ru/',
    license: 'freeware',
    color: '#E58C3A',
    popularity: 52,
    updatedDaysAgo: 20,
    tags: ['player', 'musica', 'audio', 'leve'],
    oss: ['windows'],
    archs: ['x64'],
    alternatives: ['foobar2000', 'vlc'],
    packages: [W('AIMP.AIMP')]
  }),
  a({
    slug: 'foobar2000',
    name: 'foobar2000',
    vendor: 'Peter Pawlowski',
    categorySlug: 'audio',
    tagline: 'Player de áudio modular para audiófilos.',
    description:
      'Player minimalista altamente personalizável, com suporte a formatos raros, conversão de arquivos e milhares de componentes da comunidade. Referência para quem preza qualidade e flexibilidade.',
    websiteUrl: 'https://www.foobar2000.org/',
    license: 'freeware',
    color: '#E8B33C',
    popularity: 48,
    updatedDaysAgo: 12,
    tags: ['player', 'musica', 'audio', 'audiofilo'],
    oss: ['windows'],
    archs: ['x64', 'arm64'],
    alternatives: ['aimp', 'musicbee'],
    packages: [W('PeterPawlowski.foobar2000')]
  }),
  a({
    slug: 'k-lite-codecs',
    name: 'K-Lite Codec Pack Standard',
    vendor: 'Codec Guide',
    categorySlug: 'video',
    tagline: 'Pacote de codecs para reproduzir qualquer vídeo.',
    description:
      'Coleção de codecs e filtros DirectShow que garante reprodução de praticamente qualquer formato de áudio e vídeo no Windows Media Player e players compatíveis. A versão Standard cobre 99% dos casos; evite instalar pacotes duplicados.',
    websiteUrl: 'https://codecguide.com/download_k-lite_codec_pack.htm',
    license: 'freeware',
    color: '#0080C0',
    popularity: 58,
    updatedDaysAgo: 8,
    tags: ['codecs', 'video', 'midia', 'reproducao'],
    oss: ['windows'],
    archs: ['x64'],
    alternatives: ['vlc'],
    packages: [W('CodecGuide.K-LiteCodecPack.Standard')]
  }),
  a({
    slug: 'evernote',
    name: 'Evernote',
    vendor: 'Evernote Corporation',
    categorySlug: 'produtividade',
    tagline: 'Notas e anotações sincronizadas na nuvem.',
    description:
      'Aplicativo clássico de notas com busca em PDFs e imagens, web clipper e sincronização multiplataforma. O plano gratuito limita o número de notas sincronizadas.',
    websiteUrl: 'https://evernote.com/',
    license: 'freemium',
    color: '#00A82D',
    popularity: 50,
    updatedDaysAgo: 7,
    tags: ['notas', 'produtividade', 'anotacoes'],
    oss: ['windows', 'macos'],
    archs: ['x64'],
    alternatives: ['notion', 'obsidian'],
    packages: [W('Evernote.Evernote'), BC('evernote')]
  }),
  a({
    slug: 'google-earth-pro',
    name: 'Google Earth Pro',
    vendor: 'Google',
    categorySlug: 'internet',
    tagline: 'Globo 3D gratuito com medições e histórico de imagens.',
    description:
      'Versão completa do Google Earth para desktop, gratuita desde 2015. Inclui medição de áreas, importação de GIS, histórico de imagens de satélite e gravação de tours — útil até para trabalho técnico.',
    websiteUrl: 'https://www.google.com/earth/versions/',
    license: 'freeware',
    color: '#34A853',
    popularity: 45,
    updatedDaysAgo: 25,
    tags: ['mapas', 'satelite', 'google', '3d'],
    oss: ['windows', 'macos'],
    archs: ['x64'],
    alternatives: [],
    packages: [W('Google.EarthPro'), BC('google-earth-pro')]
  }),
  a({
    slug: 'nvda',
    name: 'NVDA (NonVisual Desktop Access)',
    vendor: 'NV Access',
    categorySlug: 'utilitarios',
    tagline: 'Leitor de tela gratuito e open source.',
    description:
      'Leitor de tela para usuários cegos e com baixa visão, com síntese de voz em português e suporte a braile. Referência mundial em acessibilidade, gratuito e mantido por comunidade — essencial em máquinas para usuários com deficiência visual.',
    websiteUrl: 'https://www.nvaccess.org/',
    license: 'open_source',
    color: '#2E7CD6',
    popularity: 42,
    updatedDaysAgo: 6,
    tags: ['acessibilidade', 'leitor de tela', 'open source'],
    oss: ['windows'],
    archs: ['x64'],
    alternatives: [],
    packages: [W('NVAccess.NVDA')]
  }),
  a({
    slug: 'google-drive',
    name: 'Google Drive para Desktop',
    vendor: 'Google',
    categorySlug: 'produtividade',
    tagline: 'Sincroniza o Google Drive como unidade no sistema.',
    description:
      'Cliente oficial que monta o Google Drive como unidade virtual ou pasta espelhada no Windows/macOS, com upload de fotos do Google Fotos e atalhos de arquivos compartilhados.',
    websiteUrl: 'https://www.google.com/drive/download/',
    license: 'freemium',
    color: '#1FA463',
    popularity: 70,
    updatedDaysAgo: 5,
    tags: ['nuvem', 'sincronizacao', 'google', 'armazenamento'],
    oss: ['windows', 'macos'],
    archs: ['x64', 'arm64'],
    alternatives: ['dropbox', 'microsoft-onedrive'],
    packages: [W('Google.GoogleDrive'), BC('google-drive')]
  }),
  a({
    slug: 'microsoft-onedrive',
    name: 'Microsoft OneDrive',
    vendor: 'Microsoft',
    categorySlug: 'produtividade',
    tagline: 'Nuvem da Microsoft integrada ao Explorador de Arquivos.',
    description:
      'Sincronização de arquivos com o ecossistema Microsoft 365. Já vem embutido no Windows 10/11 — instale manualmente apenas se foi removido ou para configurar em conta nova.',
    websiteUrl: 'https://www.microsoft.com/microsoft-365/onedrive/download',
    license: 'freemium',
    color: '#0364B8',
    popularity: 66,
    updatedDaysAgo: 4,
    tags: ['nuvem', 'sincronizacao', 'microsoft', 'armazenamento'],
    oss: ['windows', 'macos'],
    archs: ['x64', 'arm64'],
    alternatives: ['google-drive', 'dropbox'],
    packages: [W('Microsoft.OneDrive'), BC('onedrive')]
  }),
  a({
    slug: 'irfanview',
    name: 'IrfanView',
    vendor: 'Irfan Skiljan',
    categorySlug: 'design',
    tagline: 'Visualizador de imagens ultraleve e rápido.',
    description:
      'Visualizador clássico do Windows: abre instantaneamente qualquer formato, faz conversão em lote, redimensionamento, recorte e captura de tela. Gratuito para uso não comercial.',
    websiteUrl: 'https://www.irfanview.com/',
    license: 'freeware',
    color: '#B02E2E',
    popularity: 55,
    updatedDaysAgo: 14,
    tags: ['imagens', 'visualizador', 'leve', 'batch'],
    oss: ['windows'],
    archs: ['x64'],
    alternatives: ['xnviewmp', 'faststone-image-viewer'],
    packages: [W('IrfanSkiljan.IrfanView')]
  }),
  a({
    slug: 'xnviewmp',
    name: 'XnView MP',
    vendor: 'XnSoft',
    categorySlug: 'design',
    tagline: 'Visualizador e organizador de imagens multiplataforma.',
    description:
      'Suporta mais de 500 formatos de imagem, com navegador em miniaturas, conversão em lote e edição básica. Versão moderna e multiplataforma do clássico XnView.',
    websiteUrl: 'https://www.xnview.com/en/xnviewmp/',
    license: 'freeware',
    color: '#2E86C1',
    popularity: 45,
    updatedDaysAgo: 18,
    tags: ['imagens', 'visualizador', 'batch', 'multiformato'],
    oss: ['windows', 'macos', 'linux'],
    archs: ['x64'],
    alternatives: ['irfanview', 'faststone-image-viewer'],
    packages: [
      W('XnSoft.XnViewMP'),
      BC('xnviewmp'),
      DL('https://www.xnview.com/en/xnviewmp/', 'linux')
    ]
  }),
  a({
    slug: 'faststone-image-viewer',
    name: 'FastStone Image Viewer',
    vendor: 'FastStone Soft',
    categorySlug: 'design',
    tagline: 'Visualizador com editor rápido e tela cheia intuitiva.',
    description:
      'Visualizador de imagens com navegação em tela cheia, edição básica (recorte, redimensionar, cores), comparação lado a lado e conversão em lote. Gratuito para uso doméstico.',
    websiteUrl: 'https://www.faststone.org/',
    license: 'freemium',
    color: '#D35400',
    popularity: 44,
    updatedDaysAgo: 30,
    tags: ['imagens', 'visualizador', 'edicao'],
    oss: ['windows'],
    archs: ['x64'],
    alternatives: ['irfanview', 'xnviewmp'],
    packages: [W('FastStone.Viewer')]
  }),
  a({
    slug: 'greenshot',
    name: 'Greenshot',
    vendor: 'Greenshot',
    categorySlug: 'utilitarios',
    tagline: 'Captura de tela com anotações e exportação flexível.',
    description:
      'Ferramenta de screenshot open source: captura região/janela/página inteira, anota direto no editor integrado e exporta para arquivo, área de transferência ou Office. Alternativa leve ao ShareX para quem quer simplicidade.',
    websiteUrl: 'https://getgreenshot.org/',
    license: 'open_source',
    color: '#4CAF50',
    popularity: 50,
    updatedDaysAgo: 40,
    tags: ['screenshot', 'captura', 'open source', 'produtividade'],
    oss: ['windows', 'macos'],
    archs: ['x64'],
    alternatives: ['sharex'],
    packages: [W('Greenshot.Greenshot'), BC('greenshot')]
  }),
  a({
    slug: 'teamviewer',
    name: 'TeamViewer',
    vendor: 'TeamViewer Germany GmbH',
    categorySlug: 'sysadmin',
    tagline: 'Acesso remoto clássico com uso gratuito pessoal.',
    description:
      'Acesso remoto, transferência de arquivos e reunião remota. O uso pessoal gratuito continua sendo porta de entrada comum em suporte — para uso comercial exige licença. Detecta e atravessa NAT sem configuração.',
    websiteUrl: 'https://www.teamviewer.com/pt-br/',
    license: 'freemium',
    color: '#0E8EE9',
    popularity: 60,
    updatedDaysAgo: 3,
    tags: ['acesso remoto', 'suporte', 'vnc', 'sysadmin'],
    oss: ['windows', 'macos', 'linux'],
    archs: ['x64'],
    alternatives: ['anydesk', 'rustdesk'],
    packages: [
      W('TeamViewer.TeamViewer'),
      BC('teamviewer'),
      DL('https://www.teamviewer.com/pt-br/download/linux/', 'linux')
    ]
  }),
  a({
    slug: 'teracopy',
    name: 'TeraCopy',
    vendor: 'Code Sector',
    categorySlug: 'utilitarios',
    tagline: 'Cópia de arquivos mais rápida e com verificação.',
    description:
      'Substitui a cópia do Windows com fila dinâmica, pausa/retomada, verificação de integridade por CRC e recuperação de erros sem abortar a transferência. Integra-se ao Explorer. Versão gratuita cobre uso doméstico.',
    websiteUrl: 'https://codesector.com/teracopy',
    license: 'freemium',
    color: '#3F51B5',
    popularity: 46,
    updatedDaysAgo: 35,
    tags: ['arquivos', 'copiar', 'verificacao', 'explorer'],
    oss: ['windows'],
    archs: ['x64'],
    alternatives: [],
    packages: [W('CodeSector.TeraCopy')]
  }),
  a({
    slug: 'revo-uninstaller',
    name: 'Revo Uninstaller Free',
    vendor: 'VS Revo Group',
    categorySlug: 'utilitarios',
    tagline: 'Desinstalação completa com varredura de resíduos.',
    description:
      'Desinstala programas e varre registro/pastas sobrando após a desinstalação padrão. Inclui ferramentas de limpeza, gerenciador de inicialização e modo forçado para programas rebeldes.',
    websiteUrl: 'https://www.revouninstaller.com/',
    license: 'freemium',
    color: '#E67E22',
    popularity: 52,
    updatedDaysAgo: 20,
    tags: ['desinstalar', 'limpeza', 'registro', 'utilitarios'],
    oss: ['windows'],
    archs: ['x64'],
    alternatives: [],
    packages: [W('RevoUninstaller.RevoUninstaller')]
  }),
  a({
    slug: 'windirstat',
    name: 'WinDirStat',
    vendor: 'WinDirStat Team',
    categorySlug: 'utilitarios',
    tagline: 'Visualize o que ocupa espaço no disco com mapa de blocos.',
    description:
      'Clássico analisador de uso de disco: escaneia a unidade e mostra um treemap colorido onde cada bloco é um arquivo. A forma mais rápida de descobrir o que está enchendo o HD/SSD.',
    websiteUrl: 'https://windirstat.net/',
    license: 'open_source',
    color: '#27AE60',
    popularity: 50,
    updatedDaysAgo: 90,
    tags: ['disco', 'espaco', 'analise', 'open source'],
    oss: ['windows'],
    archs: ['x64'],
    alternatives: ['wiztree'],
    packages: [W('WinDirStat.WinDirStat')]
  }),
  a({
    slug: 'wiztree',
    name: 'WizTree',
    vendor: 'Antibody Software',
    categorySlug: 'utilitarios',
    tagline: 'Análise de disco ultrarrápida via MFT.',
    description:
      'Faz o mesmo que o WinDirStat — mapa visual do uso do disco — porém lê a MFT do NTFS diretamente, escaneando terabytes em segundos. Gratuito para uso pessoal; versão paga remove recursos comerciais.',
    websiteUrl: 'https://wiztreefree.com/',
    license: 'freemium',
    color: '#8E44AD',
    popularity: 48,
    updatedDaysAgo: 25,
    tags: ['disco', 'espaco', 'analise', 'rapido'],
    oss: ['windows'],
    archs: ['x64'],
    alternatives: ['windirstat'],
    packages: [W('AntibodySoftware.WizTree')]
  }),
  a({
    slug: 'open-shell-menu',
    name: 'Open-Shell',
    vendor: 'Open-Shell',
    categorySlug: 'utilitarios',
    tagline: 'Menu Iniciar clássico para Windows 10/11.',
    description:
      'Fork mantido do Classic Shell: traz de volta o menu Iniciar no estilo Windows 7 com skins, busca e alta personalização. Popular entre quem migra de versões antigas ou prefere produtividade sem o menu moderno.',
    websiteUrl: 'https://github.com/Open-Shell/Open-Shell-Menu',
    license: 'open_source',
    color: '#0078D7',
    popularity: 40,
    updatedDaysAgo: 60,
    tags: ['menu iniciar', 'personalizacao', 'open source', 'classico'],
    oss: ['windows'],
    archs: ['x64'],
    alternatives: [],
    packages: [W('Open-Shell.Open-Shell-Menu')]
  }),
  a({
    slug: 'ccleaner',
    name: 'CCleaner',
    vendor: 'Gen Digital (Piriform)',
    categorySlug: 'utilitarios',
    tagline: 'Limpeza de arquivos temporários e registro.',
    description:
      'Limpa temporários, cache de navegadores e entradas de registro órfãs, além de gerenciar programas de inicialização. Use com moderação — desative telemetria nas opções e evite a limpeza de registro automática.',
    websiteUrl: 'https://www.ccleaner.com/pt-br/ccleaner',
    license: 'freemium',
    color: '#1B9CD8',
    popularity: 65,
    updatedDaysAgo: 6,
    tags: ['limpeza', 'temporarios', 'registro', 'inicializacao'],
    oss: ['windows'],
    archs: ['x64'],
    alternatives: [],
    packages: [W('Piriform.CCleaner')]
  }),
  a({
    slug: 'foxit-pdf-reader',
    name: 'Foxit PDF Reader',
    vendor: 'Foxit Software',
    categorySlug: 'pdf',
    tagline: 'Leitor de PDF leve e cheio de recursos.',
    description:
      'Alternativa completa ao Acrobat Reader: leitura rápida, anotações, preenchimento de formulários, assinatura e proteção por senha. Mais leve que o leitor da Adobe.',
    websiteUrl: 'https://www.foxit.com/pdf-reader/',
    license: 'freemium',
    color: '#FF6C37',
    popularity: 55,
    updatedDaysAgo: 9,
    tags: ['pdf', 'leitor', 'anotacoes', 'formularios'],
    oss: ['windows', 'macos'],
    archs: ['x64'],
    alternatives: ['adobe-acrobat-reader', 'sumatrapdf'],
    packages: [W('Foxit.FoxitReader')]
  }),
  a({
    slug: 'superantispyware',
    name: 'SUPERAntiSpyware Free',
    vendor: 'SUPERAntiSpyware (Support.com)',
    categorySlug: 'seguranca',
    tagline: 'Verificação dedicada de spyware e adware.',
    description:
      'Scanner complementar ao antivírus, focado em spyware, adware e trojans de navegador que o antivírus tradicional deixa passar. Use sob demanda junto ao Malwarebytes em limpezas.',
    websiteUrl: 'https://www.superantispyware.com/',
    license: 'freemium',
    color: '#C0392B',
    popularity: 38,
    updatedDaysAgo: 45,
    tags: ['spyware', 'seguranca', 'limpeza', 'scanner'],
    oss: ['windows'],
    archs: ['x64'],
    alternatives: ['malwarebytes'],
    packages: [W('SUPERAntiSpyware.SUPERAntiSpyware')]
  }),
  a({
    slug: 'winmerge',
    name: 'WinMerge',
    vendor: 'WinMerge',
    categorySlug: 'desenvolvimento',
    tagline: 'Compare e sincronize arquivos e pastas.',
    description:
      'Ferramenta open source de diff visual para arquivos texto e comparação de pastas com merge de diferenças. Útil também fora do código — comparar configs, listas e backups.',
    websiteUrl: 'https://winmerge.org/',
    license: 'open_source',
    color: '#5A9E32',
    popularity: 45,
    updatedDaysAgo: 30,
    tags: ['diff', 'comparar', 'merge', 'open source'],
    oss: ['windows'],
    archs: ['x64', 'arm64'],
    alternatives: ['visual-studio-code'],
    packages: [W('WinMerge.WinMerge')]
  })
];
