export const categories = [
  { slug: 'navegadores', name: 'Navegadores', description: 'Chrome, Firefox, Brave e alternativas', sortOrder: 10 },
  { slug: 'desenvolvimento', name: 'Desenvolvimento', description: 'Editores, IDEs e ferramentas de código', sortOrder: 20 },
  { slug: 'produtividade', name: 'Produtividade', description: 'Office, notas e organização', sortOrder: 30 },
  { slug: 'comunicacao', name: 'Comunicação', description: 'Mensageiros e reuniões', sortOrder: 40 },
  { slug: 'multimidia', name: 'Multimídia', description: 'Players e consumo de mídia', sortOrder: 50 },
  { slug: 'audio', name: 'Áudio', description: 'Música, podcasts e edição de áudio', sortOrder: 60 },
  { slug: 'video', name: 'Vídeo', description: 'Edição, gravação e conversão', sortOrder: 70 },
  { slug: 'design', name: 'Design', description: 'Imagem, vetor, 3D e UI', sortOrder: 80 },
  { slug: 'seguranca', name: 'Segurança', description: 'Criptografia e privacidade', sortOrder: 90 },
  { slug: 'gaming', name: 'Gaming', description: 'Launchers e plataformas de jogos', sortOrder: 100 },
  { slug: 'internet', name: 'Internet', description: 'Downloads e transferências', sortOrder: 110 },
  { slug: 'banco-de-dados', name: 'Banco de Dados', description: 'Clientes e administração SQL', sortOrder: 120 },
  { slug: 'virtualizacao', name: 'Virtualização', description: 'Máquinas virtuais e containers', sortOrder: 130 },
  { slug: 'utilitarios', name: 'Utilitários', description: 'Ferramentas essenciais do dia a dia', sortOrder: 140 },
  { slug: 'compactacao', name: 'Compactação', description: 'Compactadores e arquivadores', sortOrder: 150 },
  { slug: 'pdf', name: 'PDF', description: 'Leitores e editores de PDF', sortOrder: 160 },
  { slug: 'hardware', name: 'Hardware', description: 'Diagnóstico e monitoramento', sortOrder: 170 },
  { slug: 'runtimes', name: 'Runtimes', description: 'Node, Python, Java, .NET', sortOrder: 180 },
  { slug: 'terminal', name: 'Terminal', description: 'Shells e emuladores de terminal', sortOrder: 190 },
  { slug: 'devops', name: 'DevOps', description: 'Containers, CI/CD e infraestrutura', sortOrder: 200 },
  { slug: 'sysadmin', name: 'SysAdmin', description: 'Rede, acesso remoto e diagnóstico', sortOrder: 210 },
  { slug: 'ia', name: 'IA Local', description: 'Modelos e assistentes locais', sortOrder: 220 },
  { slug: 'educacao', name: 'Educação', description: 'Estudos e memorização', sortOrder: 230 }
];
